# Import et préparation du nettoyage — Citiz AURA

Ce notebook charge `regional-data/data/release/citiz_aura_final.csv` dans **`df`**, une copie de travail pandas. Une ligne représente une station et `station_uid` permet de la retrouver lors des jointures.

Utiliser le noyau **Python (IGN / OSM)** de `ign-osm/.venv`, puis exécuter les cellules dans l’ordre. Le CSV source est conservé : aucune écriture ni suppression automatique n’est effectuée.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

current_dir = Path.cwd().resolve()
root = next(
    (directory for directory in [current_dir, *current_dir.parents]
     if (directory / "regional-data/data/release/citiz_aura_final.csv").is_file()),
    None,
)
if root is None:
    raise FileNotFoundError("Cannot locate regional-data/data/release/citiz_aura_final.csv")

source_path = root / "regional-data/data/release/citiz_aura_final.csv"
# Preserve identifiers and literal text; only empty CSV cells represent missing values.
df_raw = pd.read_csv(
    source_path, encoding="utf-8-sig", sep=",",
    dtype={"station_uid": "string"}, keep_default_na=False, na_values=[""],
).convert_dtypes()
df = df_raw.copy(deep=True)
print(f"Imported {len(df):,} stations and {len(df.columns)} columns")
display(df.head())

Imported 612 stations and 50 columns

,station_uid,station_name,latitude,longitude,irve_count_500m,amenities_count_500m,amenities_count_500m_straight_line,amenities_unreachable_or_unsnapped_500m,bike_parking_count_300m,bike_parking_count_300m_straight_line,...,boundary_coverage_status,city,departement,region,reseau,capacity,num_vehicles_available,is_renting,extracted_at,station_reference_match
0,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 2ème - Parking LPA République,45.760189,4.836602,<NA>,56,323,177,5,36,...,within_region_conservative_check,<NA>,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,3,3,True,2026-10-19 14:43:54.580579+00:00,both
1,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 6ème - Bugeaud - Garibaldi,45.766689,4.851268,<NA>,1,326,0,4,61,...,within_region_conservative_check,<NA>,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,2,2,True,2026-10-19 14:43:54.580579+00:00,both
2,offre-et-disponibilite-temps-reel-du-service-c...,Sainte-Foy - Place St Luc,45.749405,4.8011,<NA>,9,29,11,1,8,...,within_region_conservative_check,<NA>,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,1,1,True,2026-10-19 14:43:54.580579+00:00,both
3,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 2ème - Charité - Auguste Comte,45.754833,4.83118,<NA>,4,262,0,1,53,...,within_region_conservative_check,<NA>,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,2,1,True,2026-10-19 14:43:54.580579+00:00,both
4,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 5ème - Quai Pierre Scize,45.766705,4.820361,<NA>,0,42,0,1,25,...,within_region_conservative_check,<NA>,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,3,3,True,2026-10-19 14:43:54.580579+00:00,both

## Premier bilan avant nettoyage

Les valeurs manquantes restent inconnues : il ne faut pas les remplacer par zéro. Les colonnes de statut expliquent notamment les indicateurs non calculés. Un zéro dans un comptage OSM indique qu’aucun objet n’a été recensé dans les données traitées, sans garantir son absence sur le terrain.

On distingue les lignes entièrement identiques des identifiants de station répétés. Les doublons sont seulement signalés : leur suppression exige d’abord de comprendre leur origine. Voir aussi `../data/release/DATA_DICTIONARY.md` et `../data/release/SOURCES.md`.

In [2]:
quality = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2),
    "unique_non_null": df.nunique(dropna=True),
}).rename_axis("column").sort_values("missing_count", ascending=False)
display(quality)

print(f"Fully duplicated rows: {df.duplicated().sum()}")
print(f"Missing station identifiers: {df['station_uid'].isna().sum()}")
duplicate_station_mask = df["station_uid"].notna() & df["station_uid"].duplicated(keep=False)
print(f"Rows with repeated station identifiers: {duplicate_station_mask.sum()}")
if duplicate_station_mask.any():
    display(df.loc[duplicate_station_mask].sort_values("station_uid"))

,dtype,missing_count,missing_percent,unique_non_null
column,,,,
accidents_count_500m,Int64,612,100.00,0
irve_count_500m,Int64,612,100.00,0
pedestrian_network_distance_m,Int64,612,100.00,0
transit_departures_peak_hour,Int64,612,100.00,0
city,Int64,612,100.00,0
public_parking_spaces_300m,Int64,555,90.69,24
amenities_count_500m_straight_line,Int64,0,0.00,229
latitude,Float64,0,0.00,606
station_name,string,0,0.00,612
station_uid,string,0,0.00,612
bike_parking_count_300m_straight_line,Int64,0,0.00,133
bike_parking_count_300m,Int64,0,0.00,81
amenities_unreachable_or_unsnapped_500m,Int64,0,0.00,252
bike_parking_unreachable_or_unsnapped_300m,Int64,0,0.00,255
tourism_sites_count_1km,Int64,0,0.00,126
tourism_sites_count_1km_straight_line,Int64,0,0.00,172
longitude,Float64,0,0.00,605
amenities_count_500m,Int64,0,0.00,142
osm_charging_sites_count_500m,Int64,0,0.00,8
tourism_unreachable_or_unsnapped_1km,Int64,0,0.00,12
parking_sites_count_300m,Int64,0,0.00,56
osm_charging_sites_count_500m_straight_line,Int64,0,0.00,22
parking_sites_count_300m_straight_line,Int64,0,0.00,91
parking_unreachable_or_unsnapped_300m,Int64,0,0.00,188
walking_station_snap_distance_m,Float64,0,0.00,606
charging_sites_unreachable_or_unsnapped_500m,Int64,0,0.00,13
public_parking_spaces_known_300m,Int64,0,0.00,197
public_parking_sites_300m,Int64,0,0.00,37
parking_sites_unknown_access_300m,Int64,0,0.00,67
public_parking_sites_unknown_capacity_300m,Int64,0,0.00,23
public_parking_spaces_300m_status,string,0,0.00,2
irve_count_500m_status,string,0,0.00,1
transit_departures_peak_hour_status,string,0,0.00,1
walking_network_status,string,0,0.00,1
pedestrian_network_distance_m_status,string,0,0.00,1
accidents_count_500m_status,string,0,0.00,1
osm_extraction_has_geometry_issues,boolean,0,0.00,1
osm_count_status,string,0,0.00,1
radius_300m_inside_ign_region,boolean,0,0.00,2
radius_500m_inside_ign_region,boolean,0,0.00,2
radius_1000m_inside_ign_region,boolean,0,0.00,2
boundary_coverage_status,string,0,0.00,2
departement,string,0,0.00,9
region,string,0,0.00,1
reseau,string,0,0.00,3
capacity,Int64,0,0.00,13
num_vehicles_available,Int64,0,0.00,8
is_renting,boolean,0,0.00,1
extracted_at,string,0,0.00,1
station_reference_match,string,0,0.00,1

Fully duplicated rows: 0
Missing station identifiers: 0
Rows with repeated station identifiers: 0

## Supprimer les colonnes avec au moins 90 % de valeurs manquantes

Une colonne est supprimée de la copie de travail `df` lorsque sa proportion de cellules manquantes atteint **90 % ou plus**. Les zéros sont des valeurs renseignées et ne comptent pas comme manquants. Le tableau ci-dessous indique les colonnes retirées et leur taux de données manquantes.

`df_raw` et le CSV source restent intacts. L’identifiant `station_uid` et les colonnes de traçabilité sont conservés s’ils sont renseignés en dessous de ce seuil.

In [3]:
missing_threshold = 0.90
missing_ratio = df.isna().mean()
columns_to_drop = missing_ratio.index[missing_ratio >= missing_threshold].tolist()
dropped_columns = pd.DataFrame({
    "missing_count": df[columns_to_drop].isna().sum(),
    "missing_percent": (missing_ratio[columns_to_drop] * 100).round(2),
}).rename_axis("column").sort_values("missing_percent", ascending=False)

df = df.drop(columns=columns_to_drop)
display(dropped_columns)
print(f"Dropped columns (at least {missing_threshold:.0%} missing): {len(columns_to_drop)}")
print(f"Remaining dataset: {len(df):,} stations and {len(df.columns)} columns")
display(df.head())

                               missing_count  missing_percent
column
irve_count_500m                          612           100.00
transit_departures_peak_hour             612           100.00
pedestrian_network_distance_m            612           100.00
accidents_count_500m                     612           100.00
city                                     612           100.00
public_parking_spaces_300m               555            90.69

Dropped columns (at least 90% missing): 6
Remaining dataset: 612 stations and 44 columns

,station_uid,station_name,latitude,longitude,amenities_count_500m,amenities_count_500m_straight_line,amenities_unreachable_or_unsnapped_500m,bike_parking_count_300m,bike_parking_count_300m_straight_line,bike_parking_unreachable_or_unsnapped_300m,...,radius_1000m_inside_ign_region,boundary_coverage_status,departement,region,reseau,capacity,num_vehicles_available,is_renting,extracted_at,station_reference_match
0,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 2ème - Parking LPA République,45.760189,4.836602,56,323,177,5,36,49,...,True,within_region_conservative_check,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,3,3,True,2026-10-19 14:43:54.580579+00:00,both
1,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 6ème - Bugeaud - Garibaldi,45.766689,4.851268,1,326,0,4,61,0,...,True,within_region_conservative_check,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,2,2,True,2026-10-19 14:43:54.580579+00:00,both
2,offre-et-disponibilite-temps-reel-du-service-c...,Sainte-Foy - Place St Luc,45.749405,4.8011,9,29,11,1,8,22,...,True,within_region_conservative_check,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,1,1,True,2026-10-19 14:43:54.580579+00:00,both
3,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 2ème - Charité - Auguste Comte,45.754833,4.83118,4,262,0,1,53,0,...,True,within_region_conservative_check,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,2,1,True,2026-10-19 14:43:54.580579+00:00,both
4,offre-et-disponibilite-temps-reel-du-service-c...,Lyon 5ème - Quai Pierre Scize,45.766705,4.820361,0,42,0,1,25,0,...,True,within_region_conservative_check,Rhône,Auvergne-Rhône-Alpes,Métropole de Lyon,3,3,True,2026-10-19 14:43:54.580579+00:00,both

## Statistiques des variables numériques

Ces statistiques portent sur les données après suppression des colonnes ayant au moins 90 % de valeurs manquantes. Pour chaque variable numérique : moyenne, écart-type d’échantillon (ddof = 1), minimum, premier quartile (25 %), médiane (50 %), troisième quartile (75 %), maximum, nombre et pourcentage de valeurs manquantes. Les calculs excluent les valeurs manquantes sans les remplacer par zéro. Les booléens sont étudiés dans le tableau qualitatif suivant.

In [4]:
numeric_data = df.select_dtypes(include="number")
numeric_stats = numeric_data.describe(percentiles=[0.25, 0.5, 0.75]).T
numeric_stats = numeric_stats.rename(columns={
    "count": "Effectif renseigné", "mean": "Moyenne", "std": "Écart-type",
    "min": "Minimum", "25%": "Q1 (25 %)", "50%": "Médiane (50 %)",
    "75%": "Q3 (75 %)", "max": "Maximum",
})
numeric_stats["Valeurs manquantes"] = numeric_data.isna().sum()
numeric_stats["Valeurs manquantes (%)"] = numeric_data.isna().mean() * 100
numeric_stats.index.name = "Variable"
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(numeric_stats.round(2))

,Effectif renseigné,Moyenne,Écart-type,Minimum,Q1 (25 %),Médiane (50 %),Q3 (75 %),Maximum,Valeurs manquantes,Valeurs manquantes (%)
Variable,,,,,,,,,,
latitude,612.0,45.54,0.33,44.82,45.19,45.58,45.77,46.37,0,0.0
longitude,612.0,5.42,0.56,3.2,4.85,5.7,5.79,6.71,0,0.0
amenities_count_500m,612.0,42.05,54.9,0.0,9.0,22.0,49.0,302.0,0,0.0
amenities_count_500m_straight_line,612.0,103.89,108.34,0.0,25.75,59.0,143.5,623.0,0,0.0
amenities_unreachable_or_unsnapped_500m,612.0,109.8,138.79,0.0,12.75,52.5,150.25,660.0,0,0.0
bike_parking_count_300m,612.0,16.93,22.15,0.0,3.0,9.0,20.0,109.0,0,0.0
bike_parking_count_300m_straight_line,612.0,38.04,37.89,0.0,10.0,25.0,53.25,176.0,0,0.0
bike_parking_unreachable_or_unsnapped_300m,612.0,147.78,221.31,0.0,12.0,55.0,156.0,952.0,0,0.0
tourism_sites_count_1km,612.0,31.03,53.45,0.0,1.0,7.0,33.0,230.0,0,0.0
tourism_sites_count_1km_straight_line,612.0,59.62,78.33,0.0,6.0,23.0,74.25,283.0,0,0.0
tourism_unreachable_or_unsnapped_1km,612.0,0.65,1.54,0.0,0.0,0.0,1.0,11.0,0,0.0
osm_charging_sites_count_500m,612.0,1.01,1.17,0.0,0.0,1.0,2.0,7.0,0,0.0
osm_charging_sites_count_500m_straight_line,612.0,2.58,3.02,0.0,1.0,2.0,3.0,23.0,0,0.0
charging_sites_unreachable_or_unsnapped_500m,612.0,2.54,2.72,0.0,0.0,2.0,4.0,12.0,0,0.0
parking_sites_count_300m,612.0,8.73,15.17,0.0,1.0,4.0,9.0,192.0,0,0.0
parking_sites_count_300m_straight_line,612.0,21.86,29.77,0.0,7.0,13.0,22.0,320.0,0,0.0
parking_unreachable_or_unsnapped_300m,612.0,74.34,110.4,0.0,18.0,40.0,81.0,988.0,0,0.0
walking_station_snap_distance_m,612.0,9.23,7.77,0.34,4.22,7.02,11.87,58.99,0,0.0
public_parking_spaces_known_300m,612.0,198.82,409.35,0.0,0.0,13.5,206.5,3433.0,0,0.0
public_parking_sites_300m,612.0,5.63,8.81,0.0,1.0,4.0,6.0,90.0,0,0.0
parking_sites_unknown_access_300m,612.0,9.05,25.38,0.0,0.0,2.0,5.0,313.0,0,0.0
public_parking_sites_unknown_capacity_300m,612.0,3.13,4.13,0.0,1.0,2.0,4.0,40.0,0,0.0
capacity,612.0,2.59,5.79,0.0,2.0,2.0,3.0,103.0,0,0.0
num_vehicles_available,612.0,1.6,1.11,0.0,1.0,1.0,2.0,7.0,0,0.0

## Statistiques des variables qualitatives et booléennes

Le résumé indique les modalités distinctes renseignées, toutes les valeurs dominantes en cas d’égalité, leur effectif et leur fréquence parmi les observations renseignées. Le tableau détaillé donne ensuite **toutes les modalités de chaque variable**, y compris les noms et identifiants de stations, avec leurs effectifs et fréquences. Les valeurs manquantes sont signalées séparément.

La fréquence renseignée utilise comme dénominateur les valeurs non manquantes de la variable. La fréquence totale utilise toutes les stations ; une ligne manquante éventuelle n’a pas de fréquence renseignée.

In [5]:
categorical_data = df.select_dtypes(exclude="number")
summary_rows = []
frequency_frames = []
for column in categorical_data:
    series = categorical_data[column]
    counts = series.value_counts(dropna=True)
    non_null_count = int(series.notna().sum())
    top_count = int(counts.max()) if not counts.empty else 0
    modes = counts.index[counts.eq(top_count)].tolist() if not counts.empty else []
    summary_rows.append({
        "Variable": column,
        "Effectif renseigné": non_null_count,
        "Valeurs manquantes": int(series.isna().sum()),
        "Modalités distinctes": len(counts),
        "Valeur(s) dominante(s)": modes,
        "Effectif par modalité dominante": top_count,
        "Fréquence dominante (%)": 100 * top_count / non_null_count if non_null_count else float("nan"),
    })
    frequencies = series.value_counts(dropna=False).rename_axis("Modalité").reset_index(name="Effectif")
    frequencies.insert(0, "Variable", column)
    frequencies["Valeur manquante"] = frequencies["Modalité"].isna()
    frequencies["Fréquence totale (%)"] = frequencies["Effectif"] / len(df) * 100
    frequencies["Fréquence renseignée (%)"] = frequencies["Effectif"] / non_null_count * 100 if non_null_count else float("nan")
    frequencies.loc[frequencies["Valeur manquante"], "Fréquence renseignée (%)"] = float("nan")
    frequency_frames.append(frequencies)

categorical_stats = pd.DataFrame(summary_rows).set_index("Variable")
category_frequencies = pd.concat(frequency_frames, ignore_index=True)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(categorical_stats.round(2))
    for column, frequencies in category_frequencies.groupby("Variable", sort=False):
        print(f"Variable: {column}")
        display(frequencies.drop(columns="Variable").reset_index(drop=True).round(2))

assert len(numeric_stats) + len(categorical_stats) == df.shape[1]
for column, frequencies in category_frequencies.groupby("Variable", sort=False):
    assert frequencies["Effectif"].sum() == len(df)
    assert abs(frequencies["Fréquence totale (%)"].sum() - 100) < 1e-8
print(f"Described {len(numeric_stats)} numeric variables and {len(categorical_stats)} categorical/boolean variables.")

,Effectif renseigné,Valeurs manquantes,Modalités distinctes,Valeur(s) dominante(s),Effectif par modalité dominante,Fréquence dominante (%)
Variable,,,,,,
station_uid,612,0,612,"[offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1115, offre-et-disponibilite-te...",1,0.16
station_name,612,0,612,"[Lyon 2ème - Parking LPA République, Lyon 6ème - Bugeaud - Garibaldi, Sainte-Foy - Place St Luc, Lyon 2ème - Charité...",1,0.16
walking_network_status,612,0,1,[matched],612,100.00
public_parking_spaces_300m_status,612,0,2,[unknown_access_or_capacity],555,90.69
irve_count_500m_status,612,0,1,[charging_units_not_defined_osm_sites_only],612,100.00
transit_departures_peak_hour_status,612,0,1,[missing_gtfs_service_date_and_peak_window],612,100.00
pedestrian_network_distance_m_status,612,0,1,[missing_origins_destinations_and_regional_graph],612,100.00
accidents_count_500m_status,612,0,1,[missing_accident_data_and_period],612,100.00
osm_count_status,612,0,1,[observed_mapped_objects_not_exhaustive],612,100.00
osm_extraction_has_geometry_issues,612,0,1,[True],612,100.00
radius_300m_inside_ign_region,612,0,2,[True],608,99.35
radius_500m_inside_ign_region,612,0,2,[True],604,98.69
radius_1000m_inside_ign_region,612,0,2,[True],592,96.73
boundary_coverage_status,612,0,2,[within_region_conservative_check],592,96.73
departement,612,0,9,[Isère],218,35.62
region,612,0,1,[Auvergne-Rhône-Alpes],612,100.00
reseau,612,0,3,[Auvergne Rhône Alpes (AURA)],411,67.16
is_renting,612,0,1,[True],612,100.00
extracted_at,612,0,1,[2026-10-19 14:43:54.580579+00:00],612,100.00
station_reference_match,612,0,1,[both],612,100.00

Variable: station_uid

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1115,1,False,0.16,0.16
1,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1116,1,False,0.16,0.16
2,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1117,1,False,0.16,0.16
3,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1118,1,False,0.16,0.16
4,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1119,1,False,0.16,0.16
5,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1120,1,False,0.16,0.16
6,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1121,1,False,0.16,0.16
7,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1122,1,False,0.16,0.16
8,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1123,1,False,0.16,0.16
9,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1124,1,False,0.16,0.16
10,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1125,1,False,0.16,0.16
11,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1126,1,False,0.16,0.16
12,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1127,1,False,0.16,0.16
13,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1128,1,False,0.16,0.16
14,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1129,1,False,0.16,0.16
15,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1130,1,False,0.16,0.16
16,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1131,1,False,0.16,0.16
17,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1132,1,False,0.16,0.16
18,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1133,1,False,0.16,0.16
19,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1134,1,False,0.16,0.16
20,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1135,1,False,0.16,0.16
21,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1136,1,False,0.16,0.16
22,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1137,1,False,0.16,0.16
23,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1138,1,False,0.16,0.16
24,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1139,1,False,0.16,0.16
25,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1140,1,False,0.16,0.16
26,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1141,1,False,0.16,0.16
27,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1142,1,False,0.16,0.16
28,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1143,1,False,0.16,0.16
29,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1144,1,False,0.16,0.16
30,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1145,1,False,0.16,0.16
31,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1146,1,False,0.16,0.16
32,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1147,1,False,0.16,0.16
33,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1148,1,False,0.16,0.16
34,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1149,1,False,0.16,0.16
35,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1150,1,False,0.16,0.16
36,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1152,1,False,0.16,0.16
37,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1153,1,False,0.16,0.16
38,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1154,1,False,0.16,0.16
39,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1155,1,False,0.16,0.16
40,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1156,1,False,0.16,0.16
41,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1157,1,False,0.16,0.16
42,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1158,1,False,0.16,0.16
43,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1159,1,False,0.16,0.16
44,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1160,1,False,0.16,0.16
45,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1161,1,False,0.16,0.16
46,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1162,1,False,0.16,0.16
47,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1165,1,False,0.16,0.16
48,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1166,1,False,0.16,0.16
49,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1167,1,False,0.16,0.16
50,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1171,1,False,0.16,0.16
51,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1172,1,False,0.16,0.16
52,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1173,1,False,0.16,0.16
53,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1174,1,False,0.16,0.16
54,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1175,1,False,0.16,0.16
55,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1176,1,False,0.16,0.16
56,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1177,1,False,0.16,0.16
57,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1178,1,False,0.16,0.16
58,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1179,1,False,0.16,0.16
59,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1180,1,False,0.16,0.16
60,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1181,1,False,0.16,0.16
61,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1182,1,False,0.16,0.16
62,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1183,1,False,0.16,0.16
63,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1215,1,False,0.16,0.16
64,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1220,1,False,0.16,0.16
65,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:1700,1,False,0.16,0.16
66,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:355,1,False,0.16,0.16
67,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:356,1,False,0.16,0.16
68,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:357,1,False,0.16,0.16
69,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:358,1,False,0.16,0.16
70,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:359,1,False,0.16,0.16
71,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:360,1,False,0.16,0.16
72,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:361,1,False,0.16,0.16
73,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:362,1,False,0.16,0.16
74,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:363,1,False,0.16,0.16
75,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:364,1,False,0.16,0.16
76,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:365,1,False,0.16,0.16
77,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:366,1,False,0.16,0.16
78,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:367,1,False,0.16,0.16
79,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:368,1,False,0.16,0.16
80,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:369,1,False,0.16,0.16
81,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:370,1,False,0.16,0.16
82,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:371,1,False,0.16,0.16
83,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:372,1,False,0.16,0.16
84,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:373,1,False,0.16,0.16
85,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:374,1,False,0.16,0.16
86,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:375,1,False,0.16,0.16
87,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:376,1,False,0.16,0.16
88,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:377,1,False,0.16,0.16
89,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:378,1,False,0.16,0.16
90,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:379,1,False,0.16,0.16
91,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:380,1,False,0.16,0.16
92,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:381,1,False,0.16,0.16
93,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:382,1,False,0.16,0.16
94,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:383,1,False,0.16,0.16
95,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:384,1,False,0.16,0.16
96,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:385,1,False,0.16,0.16
97,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:388,1,False,0.16,0.16
98,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:389,1,False,0.16,0.16
99,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:390,1,False,0.16,0.16
100,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:391,1,False,0.16,0.16
101,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:392,1,False,0.16,0.16
102,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:394,1,False,0.16,0.16
103,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:396,1,False,0.16,0.16
104,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:397,1,False,0.16,0.16
105,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:398,1,False,0.16,0.16
106,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:399,1,False,0.16,0.16
107,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:400,1,False,0.16,0.16
108,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:401,1,False,0.16,0.16
109,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:402,1,False,0.16,0.16
110,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:404,1,False,0.16,0.16
111,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:405,1,False,0.16,0.16
112,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:406,1,False,0.16,0.16
113,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:407,1,False,0.16,0.16
114,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:408,1,False,0.16,0.16
115,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:409,1,False,0.16,0.16
116,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:410,1,False,0.16,0.16
117,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:411,1,False,0.16,0.16
118,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:412,1,False,0.16,0.16
119,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:413,1,False,0.16,0.16
120,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:414,1,False,0.16,0.16
121,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:415,1,False,0.16,0.16
122,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:416,1,False,0.16,0.16
123,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:417,1,False,0.16,0.16
124,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:418,1,False,0.16,0.16
125,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:419,1,False,0.16,0.16
126,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:420,1,False,0.16,0.16
127,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:421,1,False,0.16,0.16
128,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:422,1,False,0.16,0.16
129,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:425,1,False,0.16,0.16
130,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:426,1,False,0.16,0.16
131,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:428,1,False,0.16,0.16
132,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:429,1,False,0.16,0.16
133,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:430,1,False,0.16,0.16
134,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:431,1,False,0.16,0.16
135,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:432,1,False,0.16,0.16
136,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:433,1,False,0.16,0.16
137,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:434,1,False,0.16,0.16
138,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:435,1,False,0.16,0.16
139,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:436,1,False,0.16,0.16
140,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:437,1,False,0.16,0.16
141,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:438,1,False,0.16,0.16
142,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:439,1,False,0.16,0.16
143,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:440,1,False,0.16,0.16
144,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:441,1,False,0.16,0.16
145,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:442,1,False,0.16,0.16
146,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:443,1,False,0.16,0.16
147,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:444,1,False,0.16,0.16
148,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:445,1,False,0.16,0.16
149,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:446,1,False,0.16,0.16
150,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:448,1,False,0.16,0.16
151,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:450,1,False,0.16,0.16
152,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:451,1,False,0.16,0.16
153,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:452,1,False,0.16,0.16
154,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:453,1,False,0.16,0.16
155,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:454,1,False,0.16,0.16
156,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:455,1,False,0.16,0.16
157,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:456,1,False,0.16,0.16
158,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:457,1,False,0.16,0.16
159,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:458,1,False,0.16,0.16
160,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:459,1,False,0.16,0.16
161,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:460,1,False,0.16,0.16
162,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:461,1,False,0.16,0.16
163,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:462,1,False,0.16,0.16
164,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:463,1,False,0.16,0.16
165,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:465,1,False,0.16,0.16
166,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:466,1,False,0.16,0.16
167,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:467,1,False,0.16,0.16
168,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:468,1,False,0.16,0.16
169,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:469,1,False,0.16,0.16
170,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:470,1,False,0.16,0.16
171,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:471,1,False,0.16,0.16
172,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:472,1,False,0.16,0.16
173,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:473,1,False,0.16,0.16
174,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:474,1,False,0.16,0.16
175,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:476,1,False,0.16,0.16
176,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:477,1,False,0.16,0.16
177,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:478,1,False,0.16,0.16
178,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:480,1,False,0.16,0.16
179,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:481,1,False,0.16,0.16
180,offre-et-disponibilite-temps-reel-du-service-citiz-en-autopartage-metropole-de-lyon:482,1,False,0.16,0.16

Variable: station_name

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,Lyon 2ème - Parking LPA République,1,False,0.16,0.16
1,Lyon 6ème - Bugeaud - Garibaldi,1,False,0.16,0.16
2,Sainte-Foy - Place St Luc,1,False,0.16,0.16
3,Lyon 2ème - Charité - Auguste Comte,1,False,0.16,0.16
4,Lyon 5ème - Quai Pierre Scize,1,False,0.16,0.16
5,Lyon 5ème - Valdo - Witkowski,1,False,0.16,0.16
6,Lyon 5ème - Radisson - Jaricot,1,False,0.16,0.16
7,Lyon 5ème - Place Gerson,1,False,0.16,0.16
8,Lyon 5ème - Joliot Curie,1,False,0.16,0.16
9,Lyon 5ème - Charcot-Castors,1,False,0.16,0.16
10,Lyon 1er - Bon Pasteur,1,False,0.16,0.16
11,Lyon 1er - Chartreux,1,False,0.16,0.16
12,Lyon 1er - Crimée,1,False,0.16,0.16
13,Lyon 1er - Pierre Dupont - Poudrière,1,False,0.16,0.16
14,Lyon 1er - Place Rouville,1,False,0.16,0.16
15,Lyon 1er - Quai St Vincent - Martinière,1,False,0.16,0.16
16,Lyon 7ème - Ayasse - Yves Farge,1,False,0.16,0.16
17,Lyon 7ème - Duguesclin - Rachais,1,False,0.16,0.16
18,Lyon 7ème - Jean Vallier,1,False,0.16,0.16
19,Lyon 7ème - Place Jules Guesde,1,False,0.16,0.16
20,Lyon 7ème - Rue Montesquieu,1,False,0.16,0.16
21,Lyon 7ème - Rue Rochette,1,False,0.16,0.16
22,Lyon 7ème - Simone Iff - EM Lyon,1,False,0.16,0.16
23,Lyon 4ème - Grande rue de la Croix-Rousse,1,False,0.16,0.16
24,Lyon 4ème - Place Millaud,1,False,0.16,0.16
25,Lyon 4ème - Quai Gillet-Pont Clémenceau,1,False,0.16,0.16
26,Lyon 1er - Imbert-Colomès,1,False,0.16,0.16
27,Lyon 1er - Bodin,1,False,0.16,0.16
28,La Mulatière - Fontanières,1,False,0.16,0.16
29,Saint-Genis-Laval - Hôpitaux Sud,1,False,0.16,0.16
30,Lyon 6ème - Bellecombe-Viabert,1,False,0.16,0.16
31,Lyon 6ème - Musée Guimet,1,False,0.16,0.16
32,Lyon 6ème - Vitton-Béranger,1,False,0.16,0.16
33,Lyon 6ème - Vauban-Récamier,1,False,0.16,0.16
34,Lyon 6ème - Créqui-Roosevelt,1,False,0.16,0.16
35,Lyon 6ème - Masséna,1,False,0.16,0.16
36,Lyon 3ème - Place Guichard-Bourse du Travail,1,False,0.16,0.16
37,Lyon 3ème - Garibaldi-Chaponnay,1,False,0.16,0.16
38,Lyon 3ème - Masséna-Deruelle,1,False,0.16,0.16
39,Lyon 3ème - Archives départementales,1,False,0.16,0.16
40,Lyon 3ème - Sans-Souci,1,False,0.16,0.16
41,Lyon 3ème - Docteur Rebatel,1,False,0.16,0.16
42,Lyon 3ème - Docteur Long-Vitton,1,False,0.16,0.16
43,Lyon 8ème - Antoine Lumière,1,False,0.16,0.16
44,Lyon 8ème - Mermoz-Californie,1,False,0.16,0.16
45,Lyon 8ème - Etats-Unis - Cazeneuve,1,False,0.16,0.16
46,Lyon 9ème - Observance,1,False,0.16,0.16
47,Lyon 9ème - Marietton - Pont SNCF,1,False,0.16,0.16
48,Lyon 9ème - Masaryk,1,False,0.16,0.16
49,Lyon 9ème - Sergent Berthet,1,False,0.16,0.16
50,Lyon 2ème - Place Bellecour,1,False,0.16,0.16
51,Lyon 2ème - Franklin,1,False,0.16,0.16
52,Lyon 2ème - Claudius Collonge,1,False,0.16,0.16
53,Villeurbanne - La Soie,1,False,0.16,0.16
54,Villeurbanne - Gare de Villeurbanne,1,False,0.16,0.16
55,Villeurbanne - Tonkin Nord,1,False,0.16,0.16
56,Villeurbanne - Tolstoi-Papillon,1,False,0.16,0.16
57,Villeurbanne - Salengro,1,False,0.16,0.16
58,Villeurbanne - Totem,1,False,0.16,0.16
59,Saint-Genis-les-Ollières,1,False,0.16,0.16
60,Lyon 4ème - Cours d'Herbouville,1,False,0.16,0.16
61,Lyon 4ème - Dumont D'Urville,1,False,0.16,0.16
62,Lyon 8ème - Jet d'Eau,1,False,0.16,0.16
63,Lyon 7ème - Parking LPA Tony Garnier,1,False,0.16,0.16
64,Rillieux - Ville Nouvelle,1,False,0.16,0.16
65,Lyon 3ème - Parking LPA P1 Béraudier,1,False,0.16,0.16
66,Lyon 1er - Parking LPA Terreaux,1,False,0.16,0.16
67,Lyon 3ème - Part-Dieu Lac,1,False,0.16,0.16
68,Lyon 4ème - Parking LPA Gros Caillou,1,False,0.16,0.16
69,Lyon 5ème - Parking LPA Saint-Jean,1,False,0.16,0.16
70,Lyon 2ème - Place Carnot,1,False,0.16,0.16
71,Lyon 2ème - Parking LPA Cordeliers,1,False,0.16,0.16
72,Lyon 7ème - Parking LPA Berthelot,1,False,0.16,0.16
73,Lyon 4ème - Parking LPA Croix Rousse,1,False,0.16,0.16
74,Lyon 5ème - Parking LPA Saint-Georges,1,False,0.16,0.16
75,Lyon 3ème - Parking LPA Les Halles,1,False,0.16,0.16
76,Lyon 3ème - Parking LPA La Fosse aux Ours,1,False,0.16,0.16
77,Lyon 2ème - Parking LPA Antonin Poncet,1,False,0.16,0.16
78,Lyon 6ème - Parking LPA Morand,1,False,0.16,0.16
79,Lyon 1er - Parking LPA Hotel de ville,1,False,0.16,0.16
80,Lyon 2ème - Parking LPA Saint-Antoine,1,False,0.16,0.16
81,Lyon 3ème - Saxe-Servient,1,False,0.16,0.16
82,Lyon 7ème - Jean Macé,1,False,0.16,0.16
83,Lyon 2ème - Charlemagne,1,False,0.16,0.16
84,Lyon 5ème - Point du jour,1,False,0.16,0.16
85,Lyon 9ème - Valmy,1,False,0.16,0.16
86,Lyon 9ème - Gare de Vaise,1,False,0.16,0.16
87,Lyon 9ème - Gorge de Loup,1,False,0.16,0.16
88,Villeurbanne - Charpennes,1,False,0.16,0.16
89,Lyon 8ème - Bachut - Santy,1,False,0.16,0.16
90,Lyon 7ème - Jean Jaurès,1,False,0.16,0.16
91,Lyon 1er - Place Sathonay,1,False,0.16,0.16
92,Lyon 6ème - Brotteaux,1,False,0.16,0.16
93,Lyon 5ème - Saint Just,1,False,0.16,0.16
94,Lyon 8ème - Ambroise Courtois,1,False,0.16,0.16
95,Villeurbanne - Maisons Neuves,1,False,0.16,0.16
96,Bron - Centre,1,False,0.16,0.16
97,Lyon 3ème - Albert Thomas,1,False,0.16,0.16
98,Lyon 3ème - Saxe-Gambetta,1,False,0.16,0.16
99,Tassin - Centre,1,False,0.16,0.16
100,Villeurbanne - La Doua,1,False,0.16,0.16
101,Oullins - Médiathèque,1,False,0.16,0.16
102,Lyon 2ème - Parking LPA Marché Gare,1,False,0.16,0.16
103,Lyon 2ème - Gailleton,1,False,0.16,0.16
104,Lyon 6ème - Lycée du Parc,1,False,0.16,0.16
105,Lyon 6ème - Saxe Lafayette,1,False,0.16,0.16
106,Lyon 6ème - Créqui - Duquesne,1,False,0.16,0.16
107,Lyon 6ème - Lyautey - Foch,1,False,0.16,0.16
108,Lyon 7ème - Rue de l'Université,1,False,0.16,0.16
109,Lyon 7ème - Place Saint Louis,1,False,0.16,0.16
110,Lyon 7ème - Stade de Gerland,1,False,0.16,0.16
111,Lyon 8ème - Grand Trou,1,False,0.16,0.16
112,Lyon 8ème - Grange-Blanche,1,False,0.16,0.16
113,Lyon 8ème - Marius Berliet,1,False,0.16,0.16
114,Lyon 8ème - Mermoz - Moselle,1,False,0.16,0.16
115,Lyon 8ème - Professeur Beauvisage,1,False,0.16,0.16
116,Lyon 4ème - Boulevard de la Croix-Rousse,1,False,0.16,0.16
117,Lyon 4ème - Place du Commandant Arnaud,1,False,0.16,0.16
118,Lyon 4ème - Philippe de Lassalle,1,False,0.16,0.16
119,Lyon 4ème - Denfert-Rochereau,1,False,0.16,0.16
120,Lyon 4ème - Hénon,1,False,0.16,0.16
121,Lyon 4ème - Place de la Croix-Rousse,1,False,0.16,0.16
122,Lyon 4ème - Place des Tapis,1,False,0.16,0.16
123,Lyon 8ème - Desgenettes,1,False,0.16,0.16
124,Lyon 3ème - Lacassagne,1,False,0.16,0.16
125,Lyon 3ème - Lafayette - Baraban,1,False,0.16,0.16
126,Lyon 3ème - Liberté,1,False,0.16,0.16
127,Lyon 3ème - Montchat-Lacassagne,1,False,0.16,0.16
128,Lyon 2ème - Jacobins,1,False,0.16,0.16
129,Lyon 9ème - Mangini - Muriers,1,False,0.16,0.16
130,Lyon 9ème - Saint-Rambert - Ile Barbe,1,False,0.16,0.16
131,Lyon 9ème - Vaise Bourbonnais,1,False,0.16,0.16
132,Lyon 9ème - Vaise Industrie,1,False,0.16,0.16
133,Lyon 3ème - Reconnaissance - Balzac,1,False,0.16,0.16
134,Lyon 3ème - Villette - Riboud,1,False,0.16,0.16
135,Lyon 2ème - Ainay,1,False,0.16,0.16
136,Lyon 2ème - Quai des Célestins,1,False,0.16,0.16
137,Lyon 2ème - Confluence Sud,1,False,0.16,0.16
138,Lyon 2ème - Edouard Herriot,1,False,0.16,0.16
139,Lyon 2ème - Grolée,1,False,0.16,0.16
140,Lyon 9ème - Champvert,1,False,0.16,0.16
141,Neuville sur Saône,1,False,0.16,0.16
142,Saint-Germain-au-Mont-d'Or,1,False,0.16,0.16
143,Lyon 7ème - Girondins,1,False,0.16,0.16
144,Lyon 6ème - Roosevelt - Boileau,1,False,0.16,0.16
145,Lyon 1er - Place Colbert,1,False,0.16,0.16
146,Lyon 1er - Place Morel,1,False,0.16,0.16
147,Lyon 1er - Bourse - Bât d'Argent,1,False,0.16,0.16
148,Lyon 1er - Croix-Paquet,1,False,0.16,0.16
149,Lyon 1er - Quai Saint-Vincent - Subsistances,1,False,0.16,0.16
150,Lyon 1er - Tables Claudiennes,1,False,0.16,0.16
151,Lyon 8ème - Paul Santy La Plaine,1,False,0.16,0.16
152,Lyon 7ème - Garibaldi,1,False,0.16,0.16
153,Décines - Centre,1,False,0.16,0.16
154,Meyzieu - Gare,1,False,0.16,0.16
155,Lyon 9ème - La Duchère - Martinière,1,False,0.16,0.16
156,Champagne-au-Mont-d'Or,1,False,0.16,0.16
157,Lyon 5ème - Saint-Paul,1,False,0.16,0.16
158,Lyon 5ème - Vieux-Lyon,1,False,0.16,0.16
159,Lyon 5ème - Ménival,1,False,0.16,0.16
160,Villeurbanne - Buers,1,False,0.16,0.16
161,Villeurbanne - Gratte-Ciel Nord,1,False,0.16,0.16
162,Villeurbanne - Les Brosses,1,False,0.16,0.16
163,Villeurbanne - Pôle Pixel,1,False,0.16,0.16
164,Fleurieu-sur-Saône,1,False,0.16,0.16
165,Saint-Fons - Gare,1,False,0.16,0.16
166,Villeurbanne - Parking LPA Hotel de Ville,1,False,0.16,0.16
167,Villeurbanne - République,1,False,0.16,0.16
168,Sathonay-Camp,1,False,0.16,0.16
169,Villeurbanne - Croix-Luizet,1,False,0.16,0.16
170,Villeurbanne - Cusset,1,False,0.16,0.16
171,Villeurbanne - Flachet,1,False,0.16,0.16
172,Villeurbanne - Le Tonkin - Stalingrad,1,False,0.16,0.16
173,Villeurbanne - Place Wilson,1,False,0.16,0.16
174,Villeurbanne - Saint Jean,1,False,0.16,0.16
175,Bron - Parc du Chêne,1,False,0.16,0.16
176,Villeurbanne - Grand Clément,1,False,0.16,0.16
177,Saint-Priest - Centre,1,False,0.16,0.16
178,Vénissieux - Hôtel de Ville,1,False,0.16,0.16
179,Oullins - Centre,1,False,0.16,0.16
180,Vénissieux - Moulin à Vent,1,False,0.16,0.16
181,Vénissieux - Grand Parilly,1,False,0.16,0.16
182,Craponne,1,False,0.16,0.16
183,Marcy - Centre,1,False,0.16,0.16
184,Francheville le Bas,1,False,0.16,0.16
185,Saint-Genis-Laval,1,False,0.16,0.16
186,Lyon 5ème - Ste Irénée,1,False,0.16,0.16
187,Vaulx-en-Velin - Centre ville,1,False,0.16,0.16
188,Vaulx-en-Velin - Village,1,False,0.16,0.16
189,Vaulx-en-Velin - La Soie,1,False,0.16,0.16
190,Lyon 6ème - Parking LPA Cité Internationale P2,1,False,0.16,0.16
191,Lyon 3ème - Place Danton,1,False,0.16,0.16
192,Lyon 3ème - Place Sainte-Anne,1,False,0.16,0.16
193,Couzon-au-Mont-d'Or,1,False,0.16,0.16
194,Lyon 3ème - Place de la Ferrandière,1,False,0.16,0.16
195,Lyon 3ème - Place Voltaire,1,False,0.16,0.16
196,Lyon 7ème - Sébastien Gryphe - Thibaudière,1,False,0.16,0.16
197,Lyon 7ème - Chevreul - Garibaldi,1,False,0.16,0.16
198,Lyon 4ème - Pont Churchill,1,False,0.16,0.16
199,Lyon 7ème - Gerland - Debourg,1,False,0.16,0.16
200,Gare de Massiac-Blesle,1,False,0.16,0.16
201,Couvent Sainte Cécile,1,False,0.16,0.16
202,Parc & Villages Falaise [Station électrique],1,False,0.16,0.16
203,Libération (8),1,False,0.16,0.16
204,Bd Marechal foch (51),1,False,0.16,0.16
205,Bd Maréchal Foch (2),1,False,0.16,0.16
206,Général de Gaulle (918),1,False,0.16,0.16
207,Parking Sirand,1,False,0.16,0.16
208,SNCF Gare de Grenoble - Moulin de Canel,1,False,0.16,0.16
209,Louis le Cardonnel (13),1,False,0.16,0.16
210,École Saint François La Salle - Jean Jaures,1,False,0.16,0.16
211,Victor Hugo - Lamartine,1,False,0.16,0.16
212,Dupanloup,1,False,0.16,0.16
213,Meythet-Hôtel de Ville,1,False,0.16,0.16
214,Docteur Hermite,1,False,0.16,0.16
215,SNCF Gare de Chambéry - Maréchal Leclerc (168),1,False,0.16,0.16
216,Jean Girard Madoux (32),1,False,0.16,0.16
217,Mérande (19),1,False,0.16,0.16
218,"Pierre de Coubertin (En travaux, appelez-nous pour l’adresse)",1,False,0.16,0.16
219,Mairie de Guilherand-Granges,1,False,0.16,0.16
220,Ursules (11),1,False,0.16,0.16
221,CEA - Avenue des Martyrs (71),1,False,0.16,0.16
222,MC2-Paul Claudel,1,False,0.16,0.16
223,Véhicules hors-circuit (Les véhicules sur cette station ne sont pas reservable.),1,False,0.16,0.16
224,Hôtel de Ville [Station électrique],1,False,0.16,0.16
225,CEA - Avenue des Martyrs (142),1,False,0.16,0.16
226,Le Prisme - Parking P+R,1,False,0.16,0.16
227,Granier Béalières (37),1,False,0.16,0.16
228,La Bruyère (66),1,False,0.16,0.16
229,SNCF Gare de Grenoble - Louis Weil,1,False,0.16,0.16
230,Quais de France (48),1,False,0.16,0.16
231,Régiment du génie,1,False,0.16,0.16
232,Square des fusillés (7),1,False,0.16,0.16
233,Irvoy (5),1,False,0.16,0.16
234,André Argouges,1,False,0.16,0.16
235,Alliés (66),1,False,0.16,0.16
236,Marval (2),1,False,0.16,0.16
237,Bd Clémenceau (65),1,False,0.16,0.16
238,Général Ferrié (66),1,False,0.16,0.16
239,Haxo,1,False,0.16,0.16
240,Jean Perrot (76),1,False,0.16,0.16
241,Malherbe - Pascal,1,False,0.16,0.16
242,Diables Bleus,1,False,0.16,0.16
243,Gambetta (55),1,False,0.16,0.16
244,Biollay,1,False,0.16,0.16
245,Karben - Parking P+R [Station électrique],1,False,0.16,0.16
246,Mairie de Ferney-Voltaire,1,False,0.16,0.16
247,Henri Barbusse (16) [Station électrique],1,False,0.16,0.16
248,Grand Sablon [Alizé - Cahors 7kW],1,False,0.16,0.16
249,Jean Achard [Station électrique],1,False,0.16,0.16
250,Malraux-CCI,1,False,0.16,0.16
251,Crêt de roc [Station électrique],1,False,0.16,0.16
252,Hôtel de ville,1,False,0.16,0.16
253,Hôpital,1,False,0.16,0.16
254,Place Charles de Gaulle (4),1,False,0.16,0.16
255,SNCF Gare de St-Pierre-en-Faucigny,1,False,0.16,0.16
256,Hôtel de Ville - Parking P+R [Station électrique],1,False,0.16,0.16
257,Etienne Grappe - Parking P+R [Alizé - Total 22kW],1,False,0.16,0.16
258,Nouveau Monde,1,False,0.16,0.16
259,Mairie de Saint-Genis-Pouilly,1,False,0.16,0.16
260,André Jacques - La Falaise,1,False,0.16,0.16
261,Les Prémices - Mont Blanc,1,False,0.16,0.16
262,Robespierre,1,False,0.16,0.16
263,Parking du Globe- Rue Fontaine,1,False,0.16,0.16
264,Pierre et Marie Curie (89),1,False,0.16,0.16
265,Briffaut,1,False,0.16,0.16
266,Latour Maubourg,1,False,0.16,0.16
267,Refuge,1,False,0.16,0.16
268,Quarante cinquième parallèle,1,False,0.16,0.16
269,Parking du Musée de Grenoble - 1er étage entrée Maréchal Randon,1,False,0.16,0.16
270,Pole Bus 2,1,False,0.16,0.16
271,Plan de ville,1,False,0.16,0.16
272,Parking de l'église,1,False,0.16,0.16
273,Libération (34),1,False,0.16,0.16
274,Parking Barnave,1,False,0.16,0.16
275,Balleydier - Providence,1,False,0.16,0.16
276,Rue des Martinets,1,False,0.16,0.16
277,SNCF Place de la Gare,1,False,0.16,0.16
278,Hôtel de ville Villefranche,1,False,0.16,0.16
279,Montjay,1,False,0.16,0.16
280,Macornet,1,False,0.16,0.16
281,Mairie du Veyrier-du-Lac,1,False,0.16,0.16
282,Oriel,1,False,0.16,0.16
283,Chemin des sources (10-12),1,False,0.16,0.16
284,Place Saint-Bruno,1,False,0.16,0.16
285,Cloches (2),1,False,0.16,0.16
286,Place du Commerce,1,False,0.16,0.16
287,Rue Jean Jaurès (15),1,False,0.16,0.16
288,Bissy (Mairie de),1,False,0.16,0.16
289,SNCF Gare de Voiron [Station électrique],1,False,0.16,0.16
290,Pringy - Pré Billy (Station électrique),1,False,0.16,0.16
291,Mairie de Jacob-Bellecombette,1,False,0.16,0.16
292,Asiaticus (22) (Place occupée? Ne pas se garer sur la place du marché le WE),1,False,0.16,0.16
293,AlpEspace,1,False,0.16,0.16
294,Mairie Poisat [Station électrique],1,False,0.16,0.16
295,Louis Néel,1,False,0.16,0.16
296,Plan-de-Ville,1,False,0.16,0.16
297,La monta,1,False,0.16,0.16
298,Parking des Dralis,1,False,0.16,0.16
299,SNCF Route de riottier (249),1,False,0.16,0.16
300,Rue roncevaux (201),1,False,0.16,0.16
301,Pont Rouge,1,False,0.16,0.16
302,Barrier,1,False,0.16,0.16
303,Rue de Genève (39),1,False,0.16,0.16
304,Ecole Choudy,1,False,0.16,0.16
305,Jean Monard,1,False,0.16,0.16
306,Saint-Simond,1,False,0.16,0.16
307,Mairie Varces,1,False,0.16,0.16
308,Paul Héroult,1,False,0.16,0.16
309,SNCF Gare de Sallanches,1,False,0.16,0.16
310,Parking Antoine Pissard,1,False,0.16,0.16
311,Quinzaine,1,False,0.16,0.16
312,Estacade Parking,1,False,0.16,0.16
313,Rue du Vieux Pont,1,False,0.16,0.16
314,Plateau d'Assy,1,False,0.16,0.16
315,SNCF Gare du Fayet,1,False,0.16,0.16
316,Parking Espace Bellevarde,1,False,0.16,0.16
317,Ruelle des jardins,1,False,0.16,0.16
318,"SNCF - Berthollet ( 6, avenue)",1,False,0.16,0.16
319,Stendhal-APEI,1,False,0.16,0.16
320,parking hoche,1,False,0.16,0.16
321,Bibliothèque République [Alizé - eTotem 7kW],1,False,0.16,0.16
322,Ampere (40),1,False,0.16,0.16
323,Centre bourg FLEX,1,False,0.16,0.16
324,Bibliothèque Universitaire [Alizé - eTotem 22kW],1,False,0.16,0.16
325,Parking des cristaux,1,False,0.16,0.16
326,Côte Rousse,1,False,0.16,0.16
327,ArchParc,1,False,0.16,0.16
328,Louis Vidon,1,False,0.16,0.16
329,La Dent du Chat (630),1,False,0.16,0.16
330,Gare,1,False,0.16,0.16
331,CEA Marie louise,1,False,0.16,0.16
332,Etienne BOISSON [Station électrique],1,False,0.16,0.16
333,SNCF Gare de Belleville en Beaujolais,1,False,0.16,0.16
334,Rue du Beaujolais (9),1,False,0.16,0.16
335,Rue de la Blanchisserie,1,False,0.16,0.16
336,La Revirée,1,False,0.16,0.16
337,Mairie SJA,1,False,0.16,0.16
338,Mairie de Thonon-les-Bains,1,False,0.16,0.16
339,Parking Louis Blanc,1,False,0.16,0.16
340,Les Magnolias,1,False,0.16,0.16
341,Parking de l'église,1,False,0.16,0.16
342,VRM Médiathèque,1,False,0.16,0.16
343,Place du Temple (Place occupée? Ne pas se garer sur la place du marché le WE),1,False,0.16,0.16
344,SNCF,1,False,0.16,0.16
345,Chavanelle,1,False,0.16,0.16
346,Gare SNCF de Cluses,1,False,0.16,0.16
347,Rue des Ecoles,1,False,0.16,0.16
348,Pringy - Pré Billy,1,False,0.16,0.16
349,Mairie de Barby,1,False,0.16,0.16
350,SNCF Gare de Bellegarde sur Valserine,1,False,0.16,0.16
351,Parking de la gare,1,False,0.16,0.16
352,borne électrique village,1,False,0.16,0.16
353,Gare SNCF Roman sortie Nord,1,False,0.16,0.16
354,Chemin de Jacob (141),1,False,0.16,0.16
355,Jules Ferry (1),1,False,0.16,0.16
356,Quai Pierre bayard (260),1,False,0.16,0.16
357,Chamrousse (6),1,False,0.16,0.16
358,Eaux claires (44),1,False,0.16,0.16
359,Piscine Intercommunale,1,False,0.16,0.16
360,Parking de l'Arcade,1,False,0.16,0.16
361,Rue Gabriel DIDIER,1,False,0.16,0.16
362,Centre-ville,1,False,0.16,0.16
363,marceau (7),1,False,0.16,0.16
364,Mairie de Reignier-Ésery,1,False,0.16,0.16
365,Turenne (38),1,False,0.16,0.16
366,SNCF Gare de Reignier,1,False,0.16,0.16
367,Rue des écoles (108),1,False,0.16,0.16
368,[Station temporaire] Parking du Clos Babuty,1,False,0.16,0.16
369,Mairie de Ville-la-Grand,1,False,0.16,0.16
370,Berthelot (Les balcons d’Annie),1,False,0.16,0.16
371,SNCF Baudin,1,False,0.16,0.16
372,Firmin Robert,1,False,0.16,0.16
373,SNCF Gare du Clapier - Augustin Dupré,1,False,0.16,0.16
374,Grüner [Station électrique],1,False,0.16,0.16
375,Avenue de Cran (20),1,False,0.16,0.16
376,Place des Romains-Sports,1,False,0.16,0.16
377,SNCF Gare d'Annecy - Glières,1,False,0.16,0.16
378,Denfert Rochereau,1,False,0.16,0.16
379,SNCF Gare de Chambéry,1,False,0.16,0.16
380,Albert 1er de Belgique,1,False,0.16,0.16
381,Berriat (145),1,False,0.16,0.16
382,CAF Alliés,1,False,0.16,0.16
383,Mairie de St-Martin-d'Hères,1,False,0.16,0.16
384,Bir Hakeim,1,False,0.16,0.16
385,Randon,1,False,0.16,0.16
386,Victor Hugo,1,False,0.16,0.16
387,Felix Viallet,1,False,0.16,0.16
388,Bonne,1,False,0.16,0.16
389,Joseph Vallier - Station Mobile,1,False,0.16,0.16
390,Apvril,1,False,0.16,0.16
391,Général Ferrié (20),1,False,0.16,0.16
392,Dominique Villars,1,False,0.16,0.16
393,MC2,1,False,0.16,0.16
394,Mérande Pôle Emploi,1,False,0.16,0.16
395,Belgrade,1,False,0.16,0.16
396,SNCF Gare de Grenoble - Schuman,1,False,0.16,0.16
397,Premol,1,False,0.16,0.16
398,Espace Brun - Biscuiterie,1,False,0.16,0.16
399,SNCF Gare de Grenoble - Parvis,1,False,0.16,0.16
400,Marval (1),1,False,0.16,0.16
401,Fontainades,1,False,0.16,0.16
402,Lavalette - musée,1,False,0.16,0.16
403,Pierre Semard,1,False,0.16,0.16
404,Calmette,1,False,0.16,0.16
405,St Bruno,1,False,0.16,0.16
406,Echirolles Cinéma,1,False,0.16,0.16
407,Hebert,1,False,0.16,0.16
408,CPAM Liberation (90),1,False,0.16,0.16
409,Sainte Claire - Rue de la gare,1,False,0.16,0.16
410,Stade - Piscine découverte,1,False,0.16,0.16
411,SNCF Gare de Chambéry - Poste du Verney,1,False,0.16,0.16
412,La Poste,1,False,0.16,0.16
413,Savoie Technolac,1,False,0.16,0.16
414,Rue des Fleurs - Jean Jaurès,1,False,0.16,0.16
415,Carré Curial,1,False,0.16,0.16
416,Parking P+R,1,False,0.16,0.16
417,"Chambéry le Haut, FORUM",1,False,0.16,0.16
418,Bd Marechal Joffre-park hotel,1,False,0.16,0.16
419,CHU,1,False,0.16,0.16
420,Jean Moulin,1,False,0.16,0.16
421,Eugene Delacroix,1,False,0.16,0.16
422,CEA Entrée principale,1,False,0.16,0.16
423,"Ampere, Cémoi",1,False,0.16,0.16
424,Fiancey Prédieu,1,False,0.16,0.16
425,Mayencin,1,False,0.16,0.16
426,Victor Hugo (8) T&B,1,False,0.16,0.16
427,Aigle,1,False,0.16,0.16
428,Les Granges,1,False,0.16,0.16
429,Mairie de Seyssinet,1,False,0.16,0.16
430,Narvik,1,False,0.16,0.16

Variable: walking_network_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,matched,612,False,100.0,100.0

Variable: public_parking_spaces_300m_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,unknown_access_or_capacity,555,False,90.69,90.69
1,complete_for_mapped_objects,57,False,9.31,9.31

Variable: irve_count_500m_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,charging_units_not_defined_osm_sites_only,612,False,100.0,100.0

Variable: transit_departures_peak_hour_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,missing_gtfs_service_date_and_peak_window,612,False,100.0,100.0

Variable: pedestrian_network_distance_m_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,missing_origins_destinations_and_regional_graph,612,False,100.0,100.0

Variable: accidents_count_500m_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,missing_accident_data_and_period,612,False,100.0,100.0

Variable: osm_count_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,observed_mapped_objects_not_exhaustive,612,False,100.0,100.0

Variable: osm_extraction_has_geometry_issues

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,True,612,False,100.0,100.0

Variable: radius_300m_inside_ign_region

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,True,608,False,99.35,99.35
1,False,4,False,0.65,0.65

Variable: radius_500m_inside_ign_region

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,True,604,False,98.69,98.69
1,False,8,False,1.31,1.31

Variable: radius_1000m_inside_ign_region

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,True,592,False,96.73,96.73
1,False,20,False,3.27,3.27

Variable: boundary_coverage_status

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,within_region_conservative_check,592,False,96.73,96.73
1,source_edge_coverage_not_verified,20,False,3.27,3.27

Variable: departement

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,Isère,218,False,35.62,35.62
1,Rhône,208,False,33.99,33.99
2,Savoie,70,False,11.44,11.44
3,Haute-Savoie,64,False,10.46,10.46
4,Loire,23,False,3.76,3.76
5,Drôme,19,False,3.1,3.1
6,Ain,8,False,1.31,1.31
7,Cantal,1,False,0.16,0.16
8,Ardèche,1,False,0.16,0.16

Variable: region

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,Auvergne-Rhône-Alpes,612,False,100.0,100.0

Variable: reseau

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,Auvergne Rhône Alpes (AURA),411,False,67.16,67.16
1,Métropole de Lyon,200,False,32.68,32.68
2,Développement,1,False,0.16,0.16

Variable: is_renting

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,True,612,False,100.0,100.0

Variable: extracted_at

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,2026-10-19 14:43:54.580579+00:00,612,False,100.0,100.0

Variable: station_reference_match

,Modalité,Effectif,Valeur manquante,Fréquence totale (%),Fréquence renseignée (%)
0,both,612,False,100.0,100.0

Described 24 numeric variables and 20 categorical/boolean variables.